ARG SOURCE_IMAGE=expand-mediawiki:local
FROM ${SOURCE_IMAGE} AS source_image

FROM mediawiki:1.46.0-fpm

COPY --from=source_image /var/www/html/extensions /var/www/html/extensions
COPY --from=source_image /var/www/html/skins /var/www/html/skins