ARG SOURCE_IMAGE=expand-mediawiki:local
FROM mediawiki:1.46.0-fpm

ARG SOURCE_IMAGE

COPY --from=${SOURCE_IMAGE} /var/www/html/extensions /var/www/html/extensions
COPY --from=${SOURCE_IMAGE} /var/www/html/skins /var/www/html/skins