ARG SOURCE_IMAGE=expand-mediawiki:local
FROM ${SOURCE_IMAGE}

# Remove all .git folders to reduce image size
RUN find /var/www/html/extensions /var/www/html/skins -type d -name ".git" -exec rm -rf {} +
